# 배열의 형태(shape) 변경

## reshape()을 이용한 차원 변경
- `numpy.reshape(a, newshape)` 또는 `ndarray.reshape(newshape)`
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정. 
        - 원소의 개수를 유지하는 shape으로만 변환 가능하다.
        - 원본 배열을 변경하지 않는다. (shape을 바꾼 새로운배열(카피본)을 반환) 

In [1]:
import numpy as np

In [4]:
a = np.arange(20) 
print(a.shape)
print(a.size)

(20,)
20


In [7]:
b = np.reshape(a, (4, 5)) # 함수 호출해서 
print(b.shape)
print(b.size)
b

(4, 5)
20


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
c = a.reshape((4, 5)) # 객체, 메서드 호출해서 
print(c.shape)
print(c.size)
c

(4, 5)
20


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
a # 원본을 바꾸진 않는다. 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
d = a.reshape(4, 5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
e = a.reshape(2, 2, 5) # 3차원 배열 
print(e.size) # 사이즈는 동일하다 
print(e.shape)
e

20
(2, 2, 5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [15]:
np.reshape(a, (3,3)) # 사이즈가 맞지 않는다. a.size = 20, reshape.size = 9 ? 아닌가? 

ValueError: cannot reshape array of size 20 into shape (3,3)

In [16]:
f = np.arange(5 * 5 * 5).reshape(5,5,5)
g = np.arange(3*2*7).reshape(3,2,7)

In [17]:
print(f.shape, g.shape)

(5, 5, 5) (3, 2, 7)


In [20]:
# f-> 1차원 배열로 바꾸기 
f_1 = np.reshape(f,125) # newshape에 정수를 넣으면 1차원 배열로 변환

print(f_1.shape)
f_1

(125,)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

- newshape을 지정할 때 특정 축에 -1을 주면 원소수에 맞춰서 size를 정한다. 
- 전체 축중에 하나만 사용 가능

In [22]:
f_2 = np.reshape(f, -1)  # 125 
print(f_2.shape)
f_2

(125,)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

In [24]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
a_1 = np.reshape(a, (5, -1))  # size에 맞춰서 -1값이 지정된다. 
print(a_1.shape)

(5, 4)


In [26]:
a_2 = a.reshape(2,2,-1) # 20 = 2 * 2* ? 
print(a_2.shape)

(2, 2, 5)


In [27]:
np.reshape(a_2, -1) # 1차원 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## 차원 늘리기(확장)

### numpy.newaxis 속성을 이용해 차원 늘리기
- size가 1인 rank를 늘릴때 사용한다. 
    - 지정한 axis에 size 1인 축을 추가한다.
- slicing에 사용하거나 indexing에 `...`과 같이 사용한다.
    - slicing의 경우 원하는 위치의 축을 늘릴 수 있다.
    - index에 ...과 사용하는 경우 첫번째나 마지막 축을 늘릴때 사용한다.
    

In [28]:
import numpy as np
a = np.arange(1, 6)
print(a.shape)
print(a)

(5,)
[1 2 3 4 5]


In [31]:
# (5,) => (1,5)
x = a[np.newaxis, :]
print(x.shape)
x

(1, 5)


array([[1, 2, 3, 4, 5]])

In [33]:
a # a원본은 그대로 

array([1, 2, 3, 4, 5])

In [34]:
# a: (5,) => y : (5,1)
y = a[:, np.newaxis]
print(y.shape)

(5, 1)


In [36]:
# a : (5,) -> z : (1, 5, 1)
z = a[np.newaxis, :, np.newaxis]
print(z.shape)
z

(1, 5, 1)


array([[[1],
        [2],
        [3],
        [4],
        [5]]])

In [37]:
b = np.arange(6).reshape(2,3)
print(b.shape)
b

(2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
# b : (2,3) -> m : (1, 2, 3)
m = b[np.newaxis, :]
print(m.shape)
m

(1, 2, 3)


array([[[0, 1, 2],
        [3, 4, 5]]])

In [41]:
n = b[:, :, np.newaxis]
print(n.shape)
n

(2, 3, 1)


array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [42]:
# b : (2, 3) => (2, 1, 3, 1)
o = b[:, np.newaxis, :, np.newaxis]
print(o.shape)
o

(2, 1, 3, 1)


array([[[[0],
         [1],
         [2]]],


       [[[3],
         [4],
         [5]]]])

### indexing에 ... 과 같이 사용
- ndarray[..., np.newaxis]
- 첫번째 축이나 마지막 축을 늘릴때만 사용가능

In [ ]:
(2, 3, 4) -> (1, 2, 3, 4) 앞에 축을 늘리고 싶을 때 
          -> (2, 3, 4, 1) 맨뒤에 출을 늘리고 싶을 때 
b : (2,3) -> b2 : (1, 2, 3) # 0축을 늘리기 

In [43]:
# (2, 3) -> (1, 2, 3)
b2 = b[np.newaxis, ...]
print(b2.shape)
b2

(1, 2, 3)


array([[[0, 1, 2],
        [3, 4, 5]]])

In [45]:
# (2, 3) -> (2,3, 1)
b3 = b[..., np.newaxis]
print(b3.shape)
b3

(2, 3, 1)


array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [46]:
np.reshape(b, (2,3,1))

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

### numpy.expand_dims (배열, axis)
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장한다.

In [47]:
print(a.shape)
a

(5,)


array([1, 2, 3, 4, 5])

In [51]:
# (5,) -> (5,1) 
a1 = np.expand_dims(a, axis=1)
a1.shape

(5, 1)

In [53]:
# (5,) -> (1,5)
a2 = np.expand_dims(a, axis = 0)
a2.shape

(1, 5)

In [54]:
b.shape

(2, 3)

In [57]:
# (2, 3) -> (2, 1, 3)
b1 = np.expand_dims(b, axis = 1)
b1.shape

(2, 1, 3)

## 차원 줄이기(축소)

### numpy.squeeze(배열, axis=None), 배열객체.squeeze(axis=None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank)를 줄인다.
- 제거하려는 축의 size는 1이어야 한다.
- 축을 지정하지 않으면 size가 1인 모든 축을 제거한다.
    - (3,1,1,2) => (3,2)

In [73]:
a = np.arange(12).reshape(1, 2, 2, 1, 3, 1)
a.shape

(1, 2, 2, 1, 3, 1)

In [74]:
b = np.squeeze(a)
b.shape # 1인애들 날리기 

(2, 2, 3)

In [76]:
c = np.squeeze(a, axis = 2)
c.shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [65]:
np.squeeze(a, axis =1) # size가 1이 아닌 축은 제거가 안됨

ValueError: cannot select an axis to squeeze out which has size not equal to one

### 배열객체.flatten()
- 다차원 배열을 1차원으로 만든다.

In [77]:
# (2, 3) -> (6, )
# (2, 2, 2, 3) -> (24, )
a = np.arange(20).reshape(2, 2, 5)
a.shape

(2, 2, 5)

In [78]:
a2 = a. flatten()
a2.shape

(20,)

In [79]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

## numpy.append(), numpy.insert(), numpy.delete()
- ### append(배열, 추가할값, axis=None)
    - 배열의 마지막 index에 추가할값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 추가한다.
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 index에 추가할값을 추가. 
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삽입한다.
- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할index의 값들을 삭제한다.
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삭제한다.

### append()

In [80]:
import numpy as np

a = np.array([1, 2, 3])

In [81]:
r = np.append(a, 100)
r

array([  1,   2,   3, 100])

In [84]:
r = np.append(a, [200, 300, 400]) # 여러개 값 동시에 추가, 리스트로 묶어서 전달.
r

array([  1,   2,   3, 200, 300, 400])

In [92]:
l = [
    [1, 1],
    [2, 2],
    [3, 3]
]

b = np.array(1)
print(b.shape)
b

()


array(1)

In [ ]:
# 2차원 부터는 축을 지정해야 한다. 

In [89]:
r = np.append(b, [[4,4]], axis =0) # 2차원으로 넣어줘야 한다. 
r

ValueError: zero-dimensional arrays cannot be concatenated

In [90]:
r = np.append(b, [[4, 4], [5, 5], [6, 6]], axis = 0)
r

ValueError: zero-dimensional arrays cannot be concatenated

In [91]:
b = [
    [],
    [],
    []
]


array(1)

### insert

### delete

## 배열 합치기
- ### np.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 합친다.
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 합친다. 
        - default : 0
    - 합치는 배열의 축의 개수(rank) 은 같아야 한다.
    - axis속성으로 지정한 축 이외의 축의 크기가 같아야 한다.
    - 결과의 축의개수(rank)는 대상 배열의 rank와 같다.
        - 1차원끼리 합치면 1차원결과가 나옴
- ### 합칠 대상 배열의 rank가 2일 경우(행렬) 
    - vstack()
    - hstack()
    - np.concatenate()의 간단버전
- ### vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 같아야 한다.
- ### hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 같아야 한다.

### concatenate()

- axis=0 이면 0이 늘어난다. 0을 기준으로 합치므로 (그래서 밑으로 (행이 늘어남)붙는다.)
    - 그래서 각 배열의 컬럼 수가 같아야 한다. 
- axis=1 이면 1이 늘어난다. 1을 기준으로 합치므로 (그래서 옆으로 (컬럼이 늘어남) 붙는다.)
    - 그래서 각 배열의 행수가 같아야 한다.

합치려면 ?          
a : (3, 2) / b : (3, 5) => axis = 1 (3, 7)             
b : (4, 2) / b : (4, 2) => axis = 0 (8,2) , axis = 1 (4, 4)        
a : (2, 3, 5) / b : (3, 1, 5) => 못 합침 , 3차원의 경우 최소 2개가 같아야 가능        
a : (2, 3, 5) / b : (7, 3, 5) => axis = 0 (9, 3, 5) 

In [93]:
import numpy as np

In [94]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])
c = np.array([100, 200])

## 1차원 배열 합치기

In [97]:
d = np.concatenate([a, b]) # 합치고자 하는 배열을 리스트나 튜플로 묶어 준다
d

array([ 1,  2,  3, 10, 20, 30, 40])

In [98]:
e = np.concatenate([b, a])
e

array([10, 20, 30, 40,  1,  2,  3])

In [99]:
np.concatenate([a, b, c])

array([  1,   2,   3,  10,  20,  30,  40, 100, 200])

## 2차원 배열 

In [109]:
x = np.arange(6).reshape(2,3)
y = np.arange(10, 16).reshape(2,3)
z = np.arange(20, 26).reshape(2,3)

In [110]:
r = np.concatenate([x, y], axis = 0) # (2,3) + (2,3) = (4, 3)
print(r.shape)
r

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [111]:
r = np.concatenate([x, y], axis = 1) # (2,3) + (2,3) = (2, 6)
print(r.shape)
r

(2, 6)


array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [112]:
r = np.concatenate([x, y, z], axis = 1) # (2,3) + (2,3) + (2, 3) = (2, 9)
print(r.shape)
r

(2, 9)


array([[ 0,  1,  2, 10, 11, 12, 20, 21, 22],
       [ 3,  4,  5, 13, 14, 15, 23, 24, 25]])

In [113]:
r = np.concatenate([x, y, z], axis = 0) # (2,3) + (2,3) + (2, 3) = (6, 3)
print(r.shape)
r

(6, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [20, 21, 22],
       [23, 24, 25]])

In [115]:
w = np.arange(10).reshape(2,5)
w.shape

(2, 5)

In [116]:
np.concatenate([x, w], axis = 0) # error :붙을 수가 없다. 사이즈가 안맞음. 

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [117]:
np.concatenate([x, w], axis = 1) # (2,3) + (2, 5) = (2, 8) 

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

# 3차원`

In [119]:
a = np.arange(12).reshape(2, 2, 3)
b = np.arange(2*2*7).reshape(2, 2, 7)

In [120]:
r = np.concatenate([a,b], axis = 2) # (2, 2, 3) + (2, 2, 7) = (2, 2, 10)
print(r.shape)
r

(2, 2, 10)


array([[[ 0,  1,  2,  0,  1,  2,  3,  4,  5,  6],
        [ 3,  4,  5,  7,  8,  9, 10, 11, 12, 13]],

       [[ 6,  7,  8, 14, 15, 16, 17, 18, 19, 20],
        [ 9, 10, 11, 21, 22, 23, 24, 25, 26, 27]]])

### vstack()
- 아래에 붙이는 개념이므로 열수가 맞아야 한다. 
- axis=0과 동일

In [121]:
x.shape, y.shape, z.shape

((2, 3), (2, 3), (2, 3))

In [122]:
np.vstack([x,y])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [123]:
np.vstack([x, y, z])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [20, 21, 22],
       [23, 24, 25]])

### hstack()
- 옆으로 붙이는 것이므로 행 수가 같아야 한다.
- axis=1과 동일

In [124]:
np.hstack([x, y, z])

array([[ 0,  1,  2, 10, 11, 12, 20, 21, 22],
       [ 3,  4,  5, 13, 14, 15, 23, 24, 25]])

## 배열 분할 하기
- ### split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 나눈다.. 
    - 반환값: 분할한 narray를 가진 리스트로 리턴.
    - 배열: 분할할 배열
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 같아야 한다. 

## hsplit()/vsplit()