SyntaxError: unexpected character after line continuation character (<ipython-input-1-98d1aaf48345>, line 1)

In [4]:
print("\\    /\\\n )  ( ')\n(  /  )\n \(__)|\n")

\    /\
 )  ( ')
(  /  )
 \(__)|



In [32]:
cat = """
\\    /\\
 )  ( ')
(  /  )
 \(__)|
"""
print(cat)


\    /\
 )  ( ')
(  /  )
 \(__)|



In [ ]:
|\_/|
|q p|   /}
( 0 )"""\
|"^"`    |
||_/=\\__|

In [44]:
dog = '''
|\_/|
|q p|   /}
( 0 )"""\\
|"^"`    |
||_/=\\__|
'''
print(dog)


|\_/|
|q p|   /}
( 0 )"""\
|"^"`    |
||_/=\__|



In [45]:
print("|\_/|")
print("|q p|   /}")
print("( 0 )\"\"\"\\")
print("|\"^\"`    |")
print("||_/=\\\__|")

|\_/|
|q p|   /}
( 0 )"""\
|"^"`    |
||_/=\\__|


In [46]:
a, b = map(int,input().split())
print(a+b)

1 2
3


In [ ]:
a, b = map(int,input().split())
print(a-b)

In [ ]:
n1, n2 = map(int,input().split())
# 3번이 들어갈 수 : n1 * n2의 1의자리의 수 -> 10을 나눴을 때 나머지
# 4번이 들어갈 수 : n1 * n2의 10의자리의 수 -> 10으로  
# 5번이 들어갈 수 : n1 * n2의 100의자리의 수 -> 
# 6번이 들어갈 수 : 

- N * M 크기의 얼음 받기 
- 얼음틀 모양 받기 : gragh --> 리스트로? 
- [0][0] 부터 끝까지 탐색 시작
    - 계속 쭉쭉 이어져 나가야 하니 DFS 구현
    - 상하좌우의 범위는 n과 m 사이에 있어야 한다. 
    - 상하좌우 방문해서 -> 0이면 연결 & 계속 탐색해나가기.
    - 1이면 탐색 종료. 
- 아이스크림 갯수 변수 : count = 0 

In [54]:
n, m = map(int,input().split())

graph = []
for i in range(n) : # why n ? 
    graph.append(list(map(int,input()))) # 이렇게 입력받는 건 처음인듯 
    
#DFS로 특정한 노드를 방문 한 뒤에 연결된 모든 노드들도 방문 
def dfs(x, y) : 
    # n, m 범위에서 벗어나면 즉시 종료
    if x <= -1 or x >= n or y <= -1 or y >= m :
        return False 
    # 현재 노드를 아직 방문하지 않았다면
    if graph[x][y] == 0 : 
        # 해당 노드 방문 처리 
        graph[x][y] = 1 
        # 상하좌우 위치도 모두 재귀적으로 호출
        dfs(x - 1, y)
        dfs(x + 1, y)
        dfs(x, y - 1) 
        dfs(x, y + 1) 
        return True
    return False # 여기 왜 f ? 

# 모든 노드(위치)에 대해 음료수 채우기 
result = 0 
for i in range(n) : 
    for j in range(m) :
        if dfs(i, j) == True : 
            result += 1 
            
print(result)

4 5
00110
00011
11111
00000
3


In [57]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [58]:
a % 2 

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [59]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [60]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])