# 1. 배열을 파일에 저장 및 불러오기
## 1.1 바이너리 파일로 저장/불러오기
### 1.1.1 np.save("파일경로", 배열)
- 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
- 파일명에 확장자 : npy (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)

In [1]:
import numpy as np

a = np.arange(10)
b = np.arange(12).reshape(4,3)
c = np.arange(24).reshape(4,2,3)

# 메모리에 저장되기 때문에 프로그램이 끝나면 사라지게 된다.
# 파일로 저장을 해보자. 

# 한 개의 배열 저장
np.save('a.npy', a) # 배열 a를  'a.npy' 파일로 저장
np.save('b',b) # 확장자를 생략해도 npy 확장자는 자동으로 붙는다. 
np.save('c.arr',c) # 확장자를 다르게 붙여도 npy 확장자가 자동으로 붙는다.

### 1.1.2 np.load("파일경로") 
- 파일에 저장된 배열을 불러옴

In [ ]:
# 불러오기 

a2 = np.load('a.npy')
b2 = np.load('b.npy') # 불러올때는 확장자 명까지 다 불러와야 한다. 
c2 = np.load('c.arr.npy')

### 1.1.3 np.savez("파일경로", 이름=배열, 이름=배열, ...)
- 여러개의 배열을 저장할 때 사용.
- 파일명에 확장자로 npz가 붙음.
- 내부적으로 압축해서 저장.
- load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회.

In [18]:
# 한 파일에 여러배열 저장 (압축) 
np.savez('arr.npz', one = a, two = b, three = c)

# 불러오기 
arr = np.load('arr.npz')
arr # <numpy.lib.npyio.NpzFile at 0x27128fcaa90>
arr.files # 배열의 이름들을 반환 : ['one', 'two', 'three'] 

# 딕셔너리로 조회.
a3 = arr['one']
b3 = arr['two']
c3 = arr['three']

print(a3) # [0 1 2 3 4 5 6 7 8 9]
print(b3) # [[ 0  1  2][ 3  4  5][ 6  7  8][ 9 10 11]]
print(c3) # [[[ 0  1  2] [ 3  4  5]] [[ 6  7  8] [ 9 10 11]] [[12 13 14] [15 16 17]] [[18 19 20] [21 22 23]]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


## 1.2 텍스트 파일로 저장하고 불러오기
### 1.2.1 savetxt("파일경로", 배열 [, delimiter='공백'])
- 텍스트 형태로 저장.
- 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
- 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)

### 1.2.2 loadtxt("파일경로" [,dtype=float, delimiter=공백)

In [ ]:
# 텍스트 파일로 저장 

In [22]:
np.savetxt('b.txt',b)
# np.savetxt('b.csv',b, delimiter = ',')
# np.savetxt('c.txt',c)

# b4 = np.loadtxt('b.csv',delimiter = ',')
# b4