In [1]:
import numpy as np

In [3]:
# 1. 10, 7, 5, 90, 100 을 가지는 1차원 배열을 생성.
np.array([10, 7, 5, 90, 100])
np.array((10, 7, 5, 90, 100))

array([ 10,   7,   5,  90, 100])

In [15]:
# 2. 100 ~ 200 범위의 숫자중 짝수를 가지는 배열을 생성.
a = np.arange(100, 201, 2)
print(a.shape)
a

(51,)


array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [9]:
np.linspace(100, 200, num=51)

array([100., 102., 104., 106., 108., 110., 112., 114., 116., 118., 120.,
       122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
       144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164.,
       166., 168., 170., 172., 174., 176., 178., 180., 182., 184., 186.,
       188., 190., 192., 194., 196., 198., 200.])

In [13]:
a = np.arange(100, 201)
a[a % 2 == 0]

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [19]:
# 3. 2번에서 생성한 배열과 동일한 shape에 0을 원소로 가지는 배열 생성.
b = np.zeros(shape=a.shape)
b.shape

(51,)

In [21]:
b2 = np.zeros_like(a)
print(b2.shape)
b2

(51,)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1])

In [27]:
# 4. 1001 ~ 10000 범위의 정수 중 100의 배수만 가지는 3차원 배열을 생성. (shape은 상관없음.)
a = np.arange(1000, 9999, 100).reshape(3,3,10)
print(a.shape)
a

(3, 3, 10)


array([[[1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900],
        [2000, 2100, 2200, 2300, 2400, 2500, 2600, 2700, 2800, 2900],
        [3000, 3100, 3200, 3300, 3400, 3500, 3600, 3700, 3800, 3900]],

       [[4000, 4100, 4200, 4300, 4400, 4500, 4600, 4700, 4800, 4900],
        [5000, 5100, 5200, 5300, 5400, 5500, 5600, 5700, 5800, 5900],
        [6000, 6100, 6200, 6300, 6400, 6500, 6600, 6700, 6800, 6900]],

       [[7000, 7100, 7200, 7300, 7400, 7500, 7600, 7700, 7800, 7900],
        [8000, 8100, 8200, 8300, 8400, 8500, 8600, 8700, 8800, 8900],
        [9000, 9100, 9200, 9300, 9400, 9500, 9600, 9700, 9800, 9900]]])

In [29]:
# 5. (4,4) 형태의 단위행렬(항등행렬)을 생성.
i = np.identity(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
# 6. 다음 값을 가지는 배열을 생성하고 배열의 차원수(rank)와 형태, 총 원소(element)의 개수를 조회.
# 20, 90, 80, 100, -20, 30
# 50, -10, 25, 120, -40, 90

a = np.array([[20, 90, 80, 100, -20, 30],
              [50, -10, 25, 120, -40, 90]])
print("차원수:",a.ndim)
print('형태:', a.shape)
print('원소의 개수', a.size)
print('타입:', a.dtype)

차원수: 2
형태: (2, 6)
원소의 개수 12
타입: int32


In [34]:
# 7. 정규분포를 따르는 난수를 가지는 (3,2,7) 형태의 배열을 생성. - 평균, 표준편차
np.random.normal(size=(3,2,7)) #평균:0, 표준편차:1 (-2 ~ 2)
np.random.normal(loc=100, scale=1, size=(3,2,7)) # 98 ~ 102 

array([[[100.65704068,  99.91418466, 100.82367568, 101.27639244,
         100.61531642, 100.00605177,  99.75480627],
        [ 99.77881968, 100.26420706, 100.27145918,  99.98199213,
          99.79120814,  99.60007824, 101.42405827]],

       [[100.61356604, 101.55477828, 100.50473274,  99.87989888,
         100.40946105,  99.75614578,  98.69224147],
        [100.41116168,  99.48727582,  99.02959633,  99.8263076 ,
          99.30795556, 100.1379231 , 101.84522972]],

       [[ 99.05016657, 100.0805343 , 100.67276225,  98.8373858 ,
          99.96733589,  99.78361101, 100.88234074],
        [ 99.55501115, 100.92540872,  99.77696986, 101.64933671,
          97.61981411,  99.23847312,  99.06059826]]])

In [37]:
# 8. 1 ~ 100 사이의 정수 난수를 가지는 (4, 5) 형태의 배열을 생성한 뒤 arr.npy 파일로 저장.
a = np.random.randint(1,101, (4,5))
np.save('arr.npy', a)
np.save(r'c:\temp\arr.npy', a)

In [39]:
import os
# 배열 저장 디렉토리 : backup
if not os.path.isdir('backup'):  # 현재 경로에 backup이란 디렉토리가 없냐?  없으면 디렉토리 생성
    os.mkdir('backup')
np.save('backup/arr.npy', a)    

In [41]:
a

array([[40, 99, 16, 74, 56],
       [10, 46, 62, 63, 32],
       [97, 79, 46, 57, 38],
       [39, 49, 47, 66, 67]])

In [40]:
# 9. 8번에서 저장한 arr.npy 의 배열을 불러와서 출력.
a2 = np.load('backup/arr.npy')
a2

array([[40, 99, 16, 74, 56],
       [10, 46, 62, 63, 32],
       [97, 79, 46, 57, 38],
       [39, 49, 47, 66, 67]])

In [44]:
# 10. 9번에서 불러온 배열에서 전체 값의 총합, 0번축 기준의 총합, 1번축 기준의 총합을 구하기.
print(np.sum(a2))
print(np.sum(a2, axis=0))
print(np.sum(a2, axis=1))

1083
[186 273 171 260 193]
[285 213 317 268]


In [46]:
# 11. 임의의 Boolean 값을 가지는 (5, 10) 배열을 생성하고 True의 개수를 출력하시오.
b = np.array([
    [True, False,  True, True, True, True, False,  True, True, True],
    [True, False,  True, True, True, True, False,  True, True, True],
    [True, False,  True, True, True, True, False,  True, True, True],
    [True, False,  True, True, True, True, False,  True, True, True],
    [True, False,  True, True, True, True, False,  True, True, True],
])
b.shape

(5, 10)

In [54]:
b = np.random.choice([True, False], size=(5,10))#, p=[0.1, 0.9])
print(b.shape)
np.sum(b)

(5, 10)


22

In [57]:
#True:1, False:0
a = np.random.randint(0, 2, size = (5,10), dtype=bool)
np.sum(a)

29

In [58]:
# 12-17. 아래 배열을 생성하고 12번 ~ 17번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
#  0 ~ 29 범위의 정수를 원소로 가지는 (5,6) 의 배열을 생성하고 변수에 저장.
arr = np.arange(0,30).reshape(5,6)
print(arr.shape)
arr      

(5, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [60]:
# 12. index (1,1), (2,3), (1,5)의 값들 조회
print(arr[1,1])
print(arr[2,3])
print(arr[1,5])
arr[[1,2,1] ,[1,3,5]]

7
15
11


array([ 7, 15, 11])

In [62]:
# 13. index (1,1), (1,2), (1,3), (2,1), (2,2), (2,3), (3,1), (3,2), (3,3)의 값들을 조회.
arr[1:4, 1:4]

array([[ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [64]:
arr[[1,1,1,2,2,2,3,3,3], [1,2,3]*3].reshape(3,3)

array([[ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [68]:
# 14. 13와 같은 index의 값들을 뒤집어서(reversing) 조회.
# [start:stop:-step] start > stop
r1 = arr[3:0:-1,  3:0:-1]
print(r1)


[[21 20 19]
 [15 14 13]
 [ 9  8  7]]


In [69]:
r2 = arr[1:4, 3:0:-1] # axis 1만 reversing
print(r2)

[[ 9  8  7]
 [15 14 13]
 [21 20 19]]


In [70]:
np.flip(arr) #전체

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [71]:
arr[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [73]:
r = arr[1:4, 1:4]
r

array([[ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [74]:
np.flip(r)

array([[21, 20, 19],
       [15, 14, 13],
       [ 9,  8,  7]])

In [78]:
# 15. 배열에서 15 이상의 원소만 조회해서 그 평균을 출력.
np.mean(arr[arr >= 15 ])

22.0

In [80]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [87]:
# 16. 배열에서 15이상의 원소들의 index를 조회. (0축 index, 1축 index) 형식으로 출력. 
#     ex: (0,0), (0,1) 식으로 출력
#(0축 index 배열, 1축 index 배열)
indices = np.where(arr>=15)
print(type(indices))
#zip(배열, 배열): 한번 반복시마다 두 배열의 같은 index의 값을 tuple로 묶어서 반환
for idx  in zip(indices[0], indices[1]): 
    print(idx, end=', ')
# enumerate(자료구조), zip(자료구조1, 자료구조2 [,......]), range()   

<class 'tuple'>
(2, 3), (2, 4), (2, 5), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), 

In [93]:
# 17. 배열을 axis 1을 기준으로 내림차순으로 정렬. 
# 결과
# [[ 5,  4,  3,  2,  1,  0],
#  [11, 10,  9,  8,  7,  6],
#  [17, 16, 15, 14, 13, 12],
#  [23, 22, 21, 20, 19, 18],
#  [29, 28, 27, 26, 25, 24]]   
np.sort(arr, axis=1)[:, ::-1]

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24]])

In [98]:
# 18-21. 아래 배열을 생성하고 18번 ~ 21번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
# (3, 2) shape의 배열을 생성 하시오. 
arr = np.arange(6).reshape(3,2)
print(arr.shape)

(3, 2)


In [102]:
# 18. 배열의 shape을 (1, 3, 2) 로 변환한 배열을 생성.
r1 = arr[np.newaxis, ...]
print(r1.shape)
r2 = arr[np.newaxis, :, :]
print(r2.shape)
r3 = arr.reshape(1,3,2)
print(r3.shape)
r4 = np.expand_dims(arr, axis=0)
print(r4.shape)

(1, 3, 2)
(1, 3, 2)
(1, 3, 2)
(1, 3, 2)


In [104]:
# 19. 배열의 shape을 (1, 3, 2, 1) 로 변환한 배열을 생성.
r1 = arr[np.newaxis, ..., np.newaxis]
r1.shape
r2 = arr.reshape(1,3,2,1)
r2.shape

(1, 3, 2, 1)

In [106]:
# 20. 배열을 1차원 배열로 변환한 배열을 생성.
f = arr.flatten()
f.shape

(6,)

In [108]:
# 21. 배열의 0번 축에 2개의 값을 추가. (추가된 배열의 shape: (5,2))
r = np.append(arr, [[60,70], [80,90]], axis=0)
print(r.shape)
r

(5, 2)


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [60, 70],
       [80, 90]])

In [110]:
# 1번축 기준 추가
r2 = np.append(arr, [[10,20], [40,50],[60,70]], axis=1)
print(r2.shape)
r2

(3, 4)


array([[ 0,  1, 10, 20],
       [ 2,  3, 40, 50],
       [ 4,  5, 60, 70]])

In [167]:
# 22-28. 다음 배열은 5명 학생의 국어, 영어, 수학, 과학 시험 점수이다. 행(axis=0)은 각 학생의 시험점수이고 컬럼(axis=1)은 과목을 가리킨다.
# [
#  [ 60,  80,  60, 100],
#  [ 80,  80,  90,  90],
#  [ 90,  60,  70,  50],
#  [ 40,  80,  60,  50],
#  [ 60,  50,  70, 100]
# ]
score = np.array([
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
])
print(score.shape)
score

(5, 4)


array([[ 60,  80,  60, 100],
       [ 80,  80,  90,  90],
       [ 90,  60,  70,  50],
       [ 40,  80,  60,  50],
       [ 60,  50,  70, 100]])

In [114]:
# 22. 각 과목별 평균점수를 조회.
mean_score = np.mean(score, axis=0)
mean_score

array([66., 70., 70., 78.])

In [116]:
# 23. 각 과목별 평균 점수를 성적 배열에 추가. 
np.append(score, [mean_score], axis=0)
np.append(score, [np.mean(score, axis=0)], axis=0)

array([[ 60.,  80.,  60., 100.],
       [ 80.,  80.,  90.,  90.],
       [ 90.,  60.,  70.,  50.],
       [ 40.,  80.,  60.,  50.],
       [ 60.,  50.,  70., 100.],
       [ 66.,  70.,  70.,  78.]])

In [118]:
# 24. 각 학생들의 평균 점수 조회
np.mean(score, axis=1)
np.mean(score, axis=1, keepdims=True)

array([[75. ],
       [85. ],
       [67.5],
       [57.5],
       [70. ]])

In [169]:
# 25. 과목별로 몇번째 학생의 성적이 가장 높은지 조회
np.argmax(score, axis=0)

array([2, 0, 1, 0], dtype=int64)

In [122]:
subject = np.array(['국어', '영어', '수학', '과학'])

In [125]:
# 26. 학생별로 어떤 과목의 점수가 가장 낮은지 조회.
np.argmin(score, axis=1)
subject[np.argmin(score, axis=1)]

array(['국어', '국어', '과학', '국어', '영어'], dtype='<U2')

In [135]:
# 27. 각 과목별로 편차가 가장 적은 과목과 가장 큰 과목을 조회
std_score = np.std(score, axis=0)
argmax_std = np.argmax(std_score)
argmin_std = np.argmin(std_score)
print(std_score)
print(np.round(std_score, 2)) #반올림
print(argmax_std, argmin_std)
print(subject[[argmax_std, argmin_std]])

[17.43559577 12.64911064 10.95445115 23.15167381]
[17.44 12.65 10.95 23.15]
3 2
['과학' '수학']


In [139]:
# 28. 학생들 중 과목간의 점수의 편차가 가장 적은 학생을 조회
std_score_stu = np.std(score, axis=1)
argmin_std_stu = np.argmin(std_score_stu)
argmax_std_stu = np.argmax(std_score_stu)
print(std_score_stu)
print(argmin_std_stu, argmax_std_stu)

[16.58312395  5.         14.79019946 14.79019946 18.70828693]
1 4


In [141]:
# 29-30 다음 두 배열을 가지고 29,30번 문제를 푸세요.
# A:
# [
#   [1,2,3],
#   [4,5,6],
#   [7,8,9]
# ]
# B:
# [
#   [10,20,30],
#   [40,50,60],
#   [70,80,90]
# ]
A = np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
])

B = np.array([
  [10,20,30],
  [40,50,60],
  [70,80,90]
])
print(A.shape, B.shape)

(3, 3) (3, 3)


In [144]:
# 29. 두 배열을 수직방향으로 합치기. 
C = np.concatenate([A, B], axis=0)
C2 = np.vstack([A,B]) #vstack(), hstack() : 행렬(2차원배열)
print(C.shape, C2.shape)
C

(6, 3) (6, 3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [148]:
# 30. 29에서 합친 배열을 수평방향으로 index 2를 기준으로 나누기.
D = np.split(C, [2], axis=1)
D2 = np.hsplit(C, [2]) #vsplit(), hsplit() : 2차원(행렬)
D2

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 20],
        [40, 50],
        [70, 80]]),
 array([[ 3],
        [ 6],
        [ 9],
        [30],
        [60],
        [90]])]

In [149]:
# 31-32 다음은 7명의 학생의 점수이다. 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
# [10, 50, 75, 20, 70, 50, 80]
score = np.array([10, 50, 75, 20, 70, 50, 80])
score

array([10, 50, 75, 20, 70, 50, 80])

In [152]:
# 31. 다음 배열에서 평균 이상의 점수를 받은 학생이 몇명인지 조회
mean_score = np.mean(score)
r = score[score >= mean_score]
print(mean_score) #평균점수
print(r) #평균이상을 받은 학생
print(r.size) #명수

50.714285714285715
[75 70 80]
3


In [155]:
# 평균이상인 학생수
np.sum(score>=np.mean(score))

3

In [158]:
# 32. 다음 배열에서 평균 이상의 점수를 받은 학생이 전체 학생 중 몇명인지 비율을 조회.
np.mean(score >= np.mean(score))
np.mean(score >= np.mean(score))*100

42.857142857142854

In [160]:
# 33-35 다음 배열은 스무명의 사람들의 연봉의 표본이다. (단위 만원) 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
# [7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420,
#  5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120,
#  7100, 5220, 8810, 253000]
salary = np.array([7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420,
 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120,
 7100, 5220, 8810, 253000])
salary.shape

(20,)

In [161]:
# 33. 위 배열에서 상위 75% 는 얼마 이상을 받는지 조회.
np.quantile(salary, q=0.75)

8335.0

In [162]:
# 34. 위 배열에서 하위 25%는 얼마 이하를 받는지 조회.
np.quantile(salary, q=0.25)

5080.0

In [163]:
# 4분위수: 0.25, 0.5, 0.75
np.quantile(salary, q=[0.25, 0.5, 0.75])

array([5080., 7455., 8335.])

In [164]:
np.percentile(salary, q=[25, 50, 75])

array([5080., 7455., 8335.])

In [165]:
# 35. 위 배열의 평균과 중앙값을 구하고 배열의 대푯값으로 어떤 것을 사용하는 것이 맞는지 적으세요.
salary_mean = np.mean(salary)
salary_median = np.median(salary)
print(salary_mean, salary_median)

18739.0 7455.0


In [ ]:
# 평균 > 중앙값
# 평균 < 중앙값
#많이차이가 나는 경우 : 극단값이 있는 배열, 대푯값을 중앙값.

In [166]:
np.sort(salary)

array([  1420,   2370,   2660,   4210,   4960,   5120,   5220,   5410,
         7100,   7260,   7650,   7940,   7960,   8020,   8200,   8740,
         8810,   8960,   9770, 253000])