파일명 : 이름.ipynb       
이메일: kgmyh@naver.com

In [2]:
# 1. 10, 7, 5, 90, 100 을 가지는 1차원 배열을 생성.
import numpy as np
a = np.array([10, 7, 5, 90, 100])
a

array([ 10,   7,   5,  90, 100])

In [5]:
# 2. 100 ~ 200 범위의 숫자중 짝수를 가지는 배열을 생성.
a2 = np.arange(100,201,2)
a = np.arange(100,201)
a[a%2==0]
# idx = np.array(a % 2 == 0)
# a[idx]

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [3]:
np.linspace(100,200,num=51)

array([100., 102., 104., 106., 108., 110., 112., 114., 116., 118., 120.,
       122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
       144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164.,
       166., 168., 170., 172., 174., 176., 178., 180., 182., 184., 186.,
       188., 190., 192., 194., 196., 198., 200.])

In [7]:
# 3. 2번에서 생성한 배열과 동일한 shape에 0을 원소로 가지는 배열 생성.
a3 = np.zeros(a2.shape)
a3 = np.zeros(shape=a2.shape)
a3 = np.zeros_like(a2) # 배열을 주면 쉐잎을 찾아서 배열을 만들어줌 

In [40]:
# 4. 1001 ~ 10000 범위의 정수 중 100의 배수만 가지는 3차원 배열을 생성. (shape은 상관없음.)
a4 = np.arange(1001,10001)
idx = np.array(a4 % 100 == 0)
a4[idx].size # 90 = 10 * 3 * 3
a4[idx].reshape(10, 3, 3)

array([[[ 1100,  1200,  1300],
        [ 1400,  1500,  1600],
        [ 1700,  1800,  1900]],

       [[ 2000,  2100,  2200],
        [ 2300,  2400,  2500],
        [ 2600,  2700,  2800]],

       [[ 2900,  3000,  3100],
        [ 3200,  3300,  3400],
        [ 3500,  3600,  3700]],

       [[ 3800,  3900,  4000],
        [ 4100,  4200,  4300],
        [ 4400,  4500,  4600]],

       [[ 4700,  4800,  4900],
        [ 5000,  5100,  5200],
        [ 5300,  5400,  5500]],

       [[ 5600,  5700,  5800],
        [ 5900,  6000,  6100],
        [ 6200,  6300,  6400]],

       [[ 6500,  6600,  6700],
        [ 6800,  6900,  7000],
        [ 7100,  7200,  7300]],

       [[ 7400,  7500,  7600],
        [ 7700,  7800,  7900],
        [ 8000,  8100,  8200]],

       [[ 8300,  8400,  8500],
        [ 8600,  8700,  8800],
        [ 8900,  9000,  9100]],

       [[ 9200,  9300,  9400],
        [ 9500,  9600,  9700],
        [ 9800,  9900, 10000]]])

In [12]:
a4 = np.arange(1001,10001,100).reshape(10,3,3)

(10, 3, 3)

In [41]:
# 5. (4,4) 형태의 단위행렬(항등행렬)을 생성.
a5 = np.identity(4)
a5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
# 6. 다음 값을 가지는 배열을 생성하고 배열의 차원수(rank)와 형태, 총 원소(element)의 개수를 조회.
# 20, 90, 80, 100, -20, 30
# 50, -10, 25, 120, -40, 90
a6 = np.array([[20, 90, 80, 100, -20, 30],[50, -10, 25, 120, -40, 90]])
print(a6.ndim) # rank : 2
print(a6.shape) # shape : (2,6)
print(a6.size) # size : 12 

2
(2, 6)
12


In [13]:
# 7. 정규분포를 따르는 난수를 가지는 (3,2,7) 형태의 배열을 생성.
a7 = np.random.normal(size=(3,2,7)) # 평균 : 0 , 표준편차 : 1 (-2 ~ 2사이에 있는 값들로 나온다) 
a7
# 평균을 정해주면 
np.random.normal(loc = 100, scale = 1, size = (3,2,7)) # 98 ~ 102 사이에 있는 표준편차로 

array([[[100.61081637, 101.08159337,  98.8791735 , 101.78921075,
          99.57745582,  99.60769316,  99.31050314],
        [101.2889269 , 100.63765959,  99.9694665 ,  99.19888338,
         100.04402788,  98.35078925,  99.16430893]],

       [[ 99.56723695,  99.94769296,  99.93497972,  98.71333102,
         100.89093103, 100.43697082,  97.49530276],
        [ 99.49584074,  98.55134233, 101.97998193,  98.05574953,
          98.32220777, 101.09290909, 100.44227216]],

       [[100.62702293,  98.88009804,  99.85439836, 101.96701677,
          99.28012396,  99.5623491 , 100.63820952],
        [ 98.76535707,  99.03173751, 100.56751523,  99.95027877,
         100.08149068, 100.17402828,  99.64465214]]])

In [18]:
# 8. 1 ~ 100 사이의 정수 난수를 가지는 (4, 5) 형태의 배열을 생성한 뒤 arr.npy 파일로 저장.
a8 = np.random.randint(1,101, size=(4,5))
np.save("arr.npy",a8)
# np.save(r'c:\temp\arr.npy',a) # 절대경로로 지정하기 

In [19]:
import os 
# 배열 저장 디렉토리 : backup
if not os.path.isdir('backup'): # 현재경로에 backup 디렉터리가 없니? 없으면 생성하라
    os.mkdir('backup')
np.save('backup/arr.npy',a8)

In [62]:
# 9. 8번에서 저장한 arr.npy 의 배열을 불러와서 출력.
a8_1 = np.load('arr.npy')
a8_1

array([[86, 92,  9, 30, 34],
       [88, 68, 15, 83, 61],
       [92,  6, 87,  1, 35],
       [99, 97, 16, 52, 97]])

In [235]:
# 10. 9번에서 불러온 배열에서 전체 값의 총합, 0번축 기준의 총합, 1번축 기준의 총합을 구하기.
np.sum(a8_1) # 1148
np.sum(a8_1,axis=0) # array([365, 263, 127, 166, 227])
np.sum(a8_1,axis=1) # array([251, 315, 221, 361])

array([251, 315, 221, 361])

In [258]:
# 11. 임의의 Boolean 값을 가지는 (5, 10) 배열을 생성하고 True의 개수를 출력하시오.
a11 = np.random.randint(0,2,size=(5,10))
print(a11)
np.where(a11 == True ,True,False)
len(a11[a11==True])

[[0 0 0 0 1 0 1 0 1 1]
 [1 0 1 0 1 1 1 1 1 1]
 [1 1 1 0 1 0 0 0 1 1]
 [1 0 0 1 0 1 0 1 0 0]
 [0 1 1 0 0 1 0 0 0 1]]


26

In [22]:
a11 = np.random.choice([True,False], size=(5,10))
# a11 = np.random.choice([True,False], size=(5,10), =p=[0.1, 0.9]) # 비율을 정하고 싶으면 p 설정
np.sum(a11)

33

In [25]:
a11 = np.random.randint(0, 2, size = (5,10), dtype=bool)
a11
np.sum(a11)

20

In [79]:
# 12-17. 아래 배열을 생성하고 12번 ~ 17번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
#  0 ~ 29 범위의 정수를 원소로 가지는 (5,6) 의 배열을 생성하고 변수에 저장.
a = np.arange(0,30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
# 12. index (1,1), (2,3), (1,5)의 값들 조회 : 팬싱인덱싱 -> 한번에 여러개 조회 --> 쉼표를 기준으로 [0번인덱싱],[1번인덱싱]
a[[1,2,1],[1,3,5]]

array([ 7, 15, 11])

In [39]:
# 13. index (1,1), (1,2), (1,3), (2,1), (2,2), (2,3), (3,1), (3,2), (3,3)의 값들을 조회.
a13 = a[1:4,1:4]
a13

array([[ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [45]:
# 14. 13와 같은 index의 값들을 뒤집어서(reversing) 조회. [start:stop:-step]  start > stop 
a14 = a[3:0:-1,3:0:-1]
a14

array([[21, 20, 19],
       [15, 14, 13],
       [ 9,  8,  7]])

In [46]:
# axis 1만 리버싱 
r2 = a[1:4, 3:0:-1]
r2

array([[ 9,  8,  7],
       [15, 14, 13],
       [21, 20, 19]])

In [49]:
# 전체에 대한 리버싱 --> 플립은  , [::-1]
a[::-1]
np.flip(a)
print(np.flip(a13))

[[21 20 19]
 [15 14 13]
 [ 9  8  7]]


In [52]:
# 15. 배열에서 15 이상의 원소만 조회해서 그 평균을 출력.
a15 = np.average(a[a>=15])
a15

22.0

In [61]:
# 16. 배열에서 15이상의 원소들의 index를 조회. (0축 index, 1축 index) 형식으로 출력. 
#     ex: (0,0), (0,1) 식으로 출력
indices = np.where(a>=15)

print(type(indices))

for idx in zip(indices[0],indices[1]) : # zip(배열, 배열) : 한번 반복 시 두 배열의 같은 인덱스의 값들을 반환
    print(idx, end= ' ')

<class 'tuple'>
(2, 3) (2, 4) (2, 5) (3, 0) (3, 1) (3, 2) (3, 3) (3, 4) (3, 5) (4, 0) (4, 1) (4, 2) (4, 3) (4, 4) (4, 5) 

# 유용하게 쓰니 기억하기
- enumerate(자료구조)
- zip(자료구조1, 자료구조2, [...])
- range()

In [82]:
# 17. 배열을 axis 1을 기준으로 내림차순으로 정렬. 
# 결과
[[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]   
a
# a[::,::-1] # 사실 정렬이 아님, a가 정렬이 되어 있기때문에 정렬처럼 보이는 것 
np.sort(a, axis = 1)[:,::-1]

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24]])

In [83]:
# 18-21. 아래 배열을 생성하고 18번 ~ 21번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
# (3, 2) shape의 배열을 생성 하시오. 
a = np.arange(6).reshape(3,2)

In [91]:
# 18. 배열의 shape을 (1, 3, 2) 로 변환한 배열을 생성.
# 방법1
a18_1 = a.reshape(1,3,2)
print(a18_1.shape)
#방법2 
a18_2 = a[np.newaxis,:,:]
print(a18_2.shape)
#방법3
a18_3 = a[np.newaxis, ...]
print(a18_3.shape)
#방법 4
a18_4 = np.expand_dims(a,axis=0)
print(a18_4.shape)

(1, 3, 2)
(1, 3, 2)
(1, 3, 2)
(1, 3, 2)


In [94]:
# 19. 배열의 shape을 (1, 3, 2, 1) 로 변환한 배열을 생성.
a19 = a.reshape(1,3,2,1)
print(a19.shape)

a19_1 = a[np.newaxis, ..., np.newaxis]
print(a19_1.shape)

(1, 3, 2, 1)
(1, 3, 2, 1)


In [95]:
# 20. 배열을 1차원 배열로 변환한 배열을 생성.
a20 = a.reshape(6,)
a20

f = a.flatten()
f.shape

(6,)

In [96]:
# 21. 배열의 0번 축에 2개의 값을 추가. (추가된 배열의 shape: (5,2))
a21 = np.append(a,[[6,7],[8,9]], axis = 0)
a21.shape

(5, 2)

In [98]:
#번외 
a21_1 = np.append(a,[[10,20],[40,50],[60,70]],axis=1)
print(a21_1.shape)
a21_1

(3, 4)


array([[ 0,  1, 10, 20],
       [ 2,  3, 40, 50],
       [ 4,  5, 60, 70]])

In [100]:
# 22-28. 다음 배열은 5명 학생의 국어, 영어, 수학, 과학 시험 점수이다. 행(axis=0)은 각 학생의 시험점수이고 컬럼(axis=1)은 과목을 가리킨다.
score = np.array([
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
])
score

array([[ 60,  80,  60, 100],
       [ 80,  80,  90,  90],
       [ 90,  60,  70,  50],
       [ 40,  80,  60,  50],
       [ 60,  50,  70, 100]])

In [106]:
# 22. 각 과목별 평균점수를 조회
mean_score = np.mean(score, axis=0)
mean_score

array([66., 70., 70., 78.])

In [105]:
# 23. 각 과목별 평균 점수를 성적 배열에 추가. 
np.append(score, [mean_score], axis = 0)

array([[ 60.,  80.,  60., 100.],
       [ 80.,  80.,  90.,  90.],
       [ 90.,  60.,  70.,  50.],
       [ 40.,  80.,  60.,  50.],
       [ 60.,  50.,  70., 100.],
       [ 66.,  70.,  70.,  78.]])

In [111]:
# 24. 각 학생들의 평균 점수 조회
mean_student = np.mean(score, axis = 1, keepdims=True)
mean_student

array([[75. ],
       [85. ],
       [67.5],
       [57.5],
       [70. ]])

In [113]:
# 25. 과목별로 몇번째 학생의 성적이 가장 높은지 조회
np.argmax(score,axis=0)+1 # 맥스값 인덱스 뽑기

array([3, 1, 2, 1], dtype=int64)

In [117]:
# 26. 학생별로 어떤 과목의 점수가 가장 낮은지 조회.
a26 = np.argmin(score, axis=1)

subject = np.array(['국어','영어','수학','과학']) # 팬시 인뎅싱 이용해서 과목명으로 출력해보기 
subject[a26]

array(['국어', '국어', '과학', '국어', '영어'], dtype='<U2')

In [126]:
# 27. 각 과목별로 편차가 가장 적은 과목과 가장 큰 과목을 조회
# 편차 평균 근처에서 얼마나 몰려있냐? 편차가 크다 -> 값들이 넓게 분포되어 있다. , 편차가 작다 -> 값들이 좁게 분포해있다.
std_score = np.std(score,axis = 0)

argmax_std = np.argmax(std_score)
argmin_std = np.argmin(std_score)

argmax_std, argmin_std
subject[[argmax_std, argmin_std]]

array(['과학', '수학'], dtype='<U2')

In [130]:
# 28. 학생들 중 과목간의 점수의 편차가 가장 적은 학생을 조회
std_score_stu = np.std(score, axis = 1)
argmin_std_stu = np.argmin(std_score_stu)
print(std_score_stu)
print(argmin_std_stu)

[16.58312395  5.         14.79019946 14.79019946 18.70828693]
1


In [132]:
# 29-30 다음 두 배열을 가지고 29,30번 문제를 푸세요.
A = np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
])

B = np.array([ 
  [10,20,30],
  [40,50,60],
  [70,80,90]
])

In [137]:
# 29. 두 배열을 수직방향으로 합치기. 
C = np.concatenate([A,B],axis = 0)
print(C)
AB = np.vstack([A,B]) # vstack(), hstack() : 행렬(2차원배열)에서 사용
AB

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [141]:
# 30. 29에서 합친 배열을 수평방향으로 index 2를 기준으로 나누기.
D = np.split(C, [2], axis = 1)
print(D)
a30 = np.hsplit(AB,[2])
print(a30)

[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 20],
       [40, 50],
       [70, 80]]), array([[ 3],
       [ 6],
       [ 9],
       [30],
       [60],
       [90]])]
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 20],
       [40, 50],
       [70, 80]]), array([[ 3],
       [ 6],
       [ 9],
       [30],
       [60],
       [90]])]


In [143]:
# 31-32 다음은 7명의 학생의 점수이다. 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
score = np.array([10, 50, 75, 20, 70, 50, 80])

In [151]:
# 31. 다음 배열에서 평균 이상의 점수를 받은 학생이 몇명인지 조회
mean_score = np.mean(score) # 50.71 
len(score[score >= mean_score])
print(score[score >= mean_score].size)
np.sum(score>=np.mean(score))

3


3

In [156]:
#32. 다음 배열에서 평균 이상의 점수를 받은 학생이 전체 학생 중 몇명인지 비율을 조회.
np.mean(score >= np.mean(score)) * 100

42.857142857142854

In [158]:
# 33-35 다음 배열은 스무명의 사람들의 연봉의 표본이다. (단위 만원) 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
salary = np.array([7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420,
 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120,
 7100, 5220, 8810, 253000])

In [159]:
# 33. 위 배열에서 상위 75% 는 얼마 이상을 받는지 조회.
np.quantile(salary, q=0.75) # 8740

8335.0

In [160]:
# 34. 위 배열에서 하위 25%는 얼마 이하를 받는지 조회.
np.quantile(salary, q=0.25) #4960

5080.0

In [162]:
# 35. 위 배열의 평균과 중앙값을 구하고 배열의 대푯값으로 어떤 것을 사용하는 것이 맞는지 적으세요.
salary_mean = np.mean(salary)
salary_median = np.median(salary)
print(salary_mean, salary_median)

18739.0 7455.0


In [163]:
# 평균 > 중앙값 
# 평균 < 중앙값 
# 많이 차이가 나는 경우 : 극단값이 있는 배열에서는 대푯값을 중앙값으로 사용한다. 
np.sort(salary)

array([  1420,   2370,   2660,   4210,   4960,   5120,   5220,   5410,
         7100,   7260,   7650,   7940,   7960,   8020,   8200,   8740,
         8810,   8960,   9770, 253000])