# 1. 배열의 형태(shape) 변경
## 1.1 reshape()을 이용한 차원 변경

In [1]:
import numpy as np

In [3]:
a = np.arange(20)
print(a.shape) # (20,)
print(a.size) # 20 
a # array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

(20,)
20


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
# 방법1  
b = np.reshape(a, (4,5))
print(b.shape)
print(b.size)
b 
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

(4, 5)
20


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
# 방법 2
c = a.reshape((4,5))
print(c.shape)
print(c.size)
c
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

(4, 5)
20


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
# size가 동일해야 한다.
d = a.reshape(2, 2, 5)
print(d.shape)
print(d.size)
d

(2, 2, 5)
20


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [13]:
# 3차원 배열을 1차원으로 
f = np.arange(2*2*2).reshape(2, 2, 2)
print(f.shape, f.size)

f_1 = np.reshape(f,8)      # 직접 사이즈를 입력해도됨.
f_2 = np.reshape(f,f.size) # size 호출해서 
f_3 = np.reshape(f, -1)    # -1을 주면 사이즈에 맞춰서 

print(f_1, f_1.shape)
print(f_2, f_2.shape)
print(f_2, f_2.shape)

(2, 2, 2) 8
[0 1 2 3 4 5 6 7] (8,)
[0 1 2 3 4 5 6 7] (8,)
[0 1 2 3 4 5 6 7] (8,)


In [19]:
# -1 로 입력하게 되면 사이즈에 맞춰서 reshape하게된다. 
print(a.size) # 20
a_1 = np.reshape(a, (5,-1)) # 5 * x = 20 , x = 4
print(a_1.shape) # (5,4)로 사이즈가 맞춰짐

a_2 = a.reshape(2,2,-1) # 20 = 2 * 2 * x , x = 5 
print(a_2.shape) # (2, 2, 5) 

20
(5, 4)
(2, 2, 5)


## 1.2 차원늘리기(확장) numpy.newaxis()

In [20]:
import numpy as np

In [21]:
a = np.arange(1, 6)
print(a.shape)
print(a)

(5,)
[1 2 3 4 5]


In [24]:
# (5,) 1차원에서 (1,5) 2차원으로 확장
x = a[np.newaxis, :] # [추가 , 기존]
print(x.shape) # (1, 5)
x

(1, 5)


array([[1, 2, 3, 4, 5]])

In [25]:
# (5,) 1차원에서 (5,1) 2차원으로 확장
y = a[:,np.newaxis]
print(y.shape) # (5, 1) 
y

(5, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [28]:
# (5,) 1차원에서 (1, 5, 1, 1, 1) 5차원으로 확장
z = a[np.newaxis, : , np.newaxis, np.newaxis, np.newaxis]
print(z.shape)
z

(1, 5, 1, 1, 1)


array([[[[[1]]],


        [[[2]]],


        [[[3]]],


        [[[4]]],


        [[[5]]]]])

In [29]:
# 2차원에서 3차원으로 확장하기 
b =np.arange(6).reshape(2,3)

# (2,3) -> (1, 2, 3)으로 확장하기
m = b[np.newaxis, :, :] # 갯수 맞춰서 : 넣어줘야함 
print(m.shape) # 1, 2, 3) 
m
array([[[0, 1, 2],
        [3, 4, 5]]])

(1, 2, 3)


array([[[0, 1, 2],
        [3, 4, 5]]])

In [30]:
# (2,3) -> (2, 3, 1)으로 확장하기 
n = b[:, :, np.newaxis]
print(n.shape) # (2, 3, 1)
n
array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

(2, 3, 1)


array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [31]:
# (2,3) -> (2, 1, 3, 1)
o = b[:, np.newaxis, :, np.newaxis]
print(o.shape) # (2, 1, 3, 1) 
o
array([[[[0],
         [1],
         [2]]],


       [[[3],
         [4],
         [5]]]])

(2, 1, 3, 1)


array([[[[0],
         [1],
         [2]]],


       [[[3],
         [4],
         [5]]]])

## 1.3 indexing에 ... 사용 
- 첫번째 축이나 마지막 축을 늘릴때만 사용가능

In [ ]:
(2, 3, 4) -> (1, 2, 3, 4)
          -> (2, 3, 4, 1) 

In [35]:
# (2, 3) -> (1, 2, 3) 0축 늘리기
print(b.shape)
b2 = b[np.newaxis, ...]
print(b2.shape)
b2

(2, 3)
(1, 2, 3)


array([[[0, 1, 2],
        [3, 4, 5]]])

In [37]:
# (2, 3) -> (2, 3, 1) 
b3 = b[..., np.newaxis]
print(b3.shape) # (2, 3, 1)
b3
array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

(2, 3, 1)


array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

## 1.4 numpy.expand_dims()
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장

### 1차원에서 2차원 확장하기

In [38]:
# (5,) -> (5,1)
a1 = np.expand_dims(a, axis = 1) 
a1.shape

(5, 1)

In [39]:
# (5,) -> (1,5)
a2 = np.expand_dims(a, axis = 0)
a2.shape

(1, 5)

### 2차원에서 3차원 확장하기

In [42]:
# (2,3) -> (2,1,3)
print(b.shape)
b1 = np.expand_dims(b, axis = 1)
print(b1.shape)

(2, 3)
(2, 1, 3)


### 1.5 차원줄이기(축소) : numpy.squeeze

In [43]:
a = np.arange(12).reshape(1, 2, 1, 2, 3, 1)
a.shape

(1, 2, 1, 2, 3, 1)

In [45]:
b = np.squeeze(a) # 축을 지정하지 않으면 size가 1인 모든 축을 제거
b.shape

(2, 2, 3)

In [47]:
c = np.squeeze(a, axis = 2) 
c.shape # (1, 2, 2, 3, 1)

(1, 2, 2, 3, 1)

In [49]:
# size가 1이 아닌 축은 제거가 안됨
np.squeeze(a, axis = 1) 

ValueError: cannot select an axis to squeeze out which has size not equal to one

## 1.6 flatten()
- 다차원 배열을 1차원으로 만든다

In [58]:
# (2, 2, 5) -> (20,)
a = np.arange(20).reshape(2, 2, 5)
print(a.shape) # (2, 2, 5)
a1 =a.flatten()
print(a1.shape) # (20,)

(2, 2, 5)
(20,)


## 1.7 numpy .append() 
```python
np.append(배열, 추가할값, axis=None)
```
- 배열의 마지막 index에 추가할 값을 추가
- axis : 축지정
    - None (기본값), flatten한 뒤 추가한다

In [63]:
import numpy as np

a = np.array([1,2,3])

In [64]:
# 1개의 값을 추가
r = np.append(a, 100) 
r # array([  1,   2,   3, 100])

array([  1,   2,   3, 100])

In [65]:
# 여러개 값을 리스트로 묶어서 추가
r = np.append(a, [200, 300, 400])
r # array([  1,   2,   3, 200, 300, 400])

array([  1,   2,   3, 200, 300, 400])

In [67]:
l = [
    [1, 1],
    [2, 2],
    [3, 3]
]
b = np.array(l)
print(b.shape) # (3, 2)
b

(3, 2)


array([[1, 1],
       [2, 2],
       [3, 3]])

In [70]:
# axis = 0 값에 [4,4] 추가하기 : (3,2) -> (4,2) 
r = np.append(b, [[4, 4]], axis = 0)
print(r.shape) # (4, 2)
r

(4, 2)


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [73]:
# axis = 0 에 [4,4],[5,5],[6,6] 추가하기 : (3,2) -> (6,2)
r = np.append(b, [[4, 4], [5, 5], [6, 6]], axis = 0)
print(r.shape) # (6, 2)
r

(6, 2)


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

## 1.8 numpy.insert() 

## 1.9 numpy.delete()