SyntaxError: unexpected character after line continuation character (<ipython-input-1-98d1aaf48345>, line 1)

In [4]:
print("\\    /\\\n )  ( ')\n(  /  )\n \(__)|\n")

\    /\
 )  ( ')
(  /  )
 \(__)|



In [32]:
cat = """
\\    /\\
 )  ( ')
(  /  )
 \(__)|
"""
print(cat)


\    /\
 )  ( ')
(  /  )
 \(__)|



In [ ]:
|\_/|
|q p|   /}
( 0 )"""\
|"^"`    |
||_/=\\__|

In [44]:
dog = '''
|\_/|
|q p|   /}
( 0 )"""\\
|"^"`    |
||_/=\\__|
'''
print(dog)


|\_/|
|q p|   /}
( 0 )"""\
|"^"`    |
||_/=\__|



In [45]:
print("|\_/|")
print("|q p|   /}")
print("( 0 )\"\"\"\\")
print("|\"^\"`    |")
print("||_/=\\\__|")

|\_/|
|q p|   /}
( 0 )"""\
|"^"`    |
||_/=\\__|


In [46]:
a, b = map(int,input().split())
print(a+b)

1 2
3


In [ ]:
a, b = map(int,input().split())
print(a-b)

In [ ]:
n1, n2 = map(int,input().split())
# 3번이 들어갈 수 : n1 * n2의 1의자리의 수 -> 10을 나눴을 때 나머지
# 4번이 들어갈 수 : n1 * n2의 10의자리의 수 -> 10으로  
# 5번이 들어갈 수 : n1 * n2의 100의자리의 수 -> 
# 6번이 들어갈 수 : 

- N * M 크기의 얼음 받기 
- 얼음틀 모양 받기 : gragh --> 리스트로? 
- [0][0] 부터 끝까지 탐색 시작
    - 계속 쭉쭉 이어져 나가야 하니 DFS 구현
    - 상하좌우의 범위는 n과 m 사이에 있어야 한다. 
    - 상하좌우 방문해서 -> 0이면 연결 & 계속 탐색해나가기.
    - 1이면 탐색 종료. 
- 아이스크림 갯수 변수 : count = 0 

In [54]:
n, m = map(int,input().split())

graph = []
for i in range(n) : # why n ? 
    graph.append(list(map(int,input()))) # 이렇게 입력받는 건 처음인듯 
    
#DFS로 특정한 노드를 방문 한 뒤에 연결된 모든 노드들도 방문 
def dfs(x, y) : 
    # n, m 범위에서 벗어나면 즉시 종료
    if x <= -1 or x >= n or y <= -1 or y >= m :
        return False 
    # 현재 노드를 아직 방문하지 않았다면
    if graph[x][y] == 0 : 
        # 해당 노드 방문 처리 
        graph[x][y] = 1 
        # 상하좌우 위치도 모두 재귀적으로 호출
        dfs(x - 1, y)
        dfs(x + 1, y)
        dfs(x, y - 1) 
        dfs(x, y + 1) 
        return True
    return False # 여기 왜 f ? 

# 모든 노드(위치)에 대해 음료수 채우기 
result = 0 
for i in range(n) : 
    for j in range(m) :
        if dfs(i, j) == True : 
            result += 1 
            
print(result)

4 5
00110
00011
11111
00000
3


In [57]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [58]:
a % 2 

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [59]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [60]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [8]:
# 방법2 : 인트값을 한글자씩 뽑는 방법 없나? 

234


['2', '3', '4']

In [21]:
# 각자리 수 구하기 
a = 385
lst = [i for i in str(a)]
int(lst[0])

3

In [44]:
num1, num2 = map(int,input().split())

2360
3776
1416
181720


In [49]:
hour_lst = [i for i in range(24)]
print(hour_lst)

min_lst = [i for i in range(60)]
print(min_lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]


In [51]:
H = 23
M = 40 
H in hour_lst
M in min_lst

True

In [53]:
hour_lst[-1]

23

In [57]:
num = int(input())
scope = range(1,10) 
list(scope)

2


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [67]:
[i for i in scope if num in scope]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [76]:
num = int(input())

if num in range(1,10) : 
    for i in range(1,10) : 
        print(f'{num} * {i} = {num * i}')

3
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27


In [88]:
case = int(input())
tmp = list()

for _ in range(case):
    A, B = map(int, input().split())    # 입력받은 값들을 tmp 에 일시적으로 저장한다.
    tmp.append(A)
    tmp.append(B)
# print(tmp)

for i in range(0,len(tmp),2):
    print(tmp[i]+tmp[i+1])

5
1 1
2 3 
4 5
9 8
5 2
2
5
9
17
7


In [79]:
print(tmp)

[1, 2, 3, 4, 5, 6]


In [81]:
tmp[0]+tmp[1]

3

In [93]:
num = int(input())
print(sum([i for i in range(1,num+1)]))

3
6


In [96]:
num = int(input())
for i in range(1, num + 1):
    print('*' * i)

5
*
**
***
****
*****


In [97]:
str = '*'
str.rjust(5)

'    *'

In [99]:
num = int(input())

for i in range(1, num+1):
    str = '*' * i
    print(str.rjust(num))

4
   *
  **
 ***
****


In [11]:
a = 150
b = 266
c = 427

num = a * b * c 
lst = list(str(num))
print(lst)

# 각자리수의 값 별로 카운트 
lst.count(str(lst[0]))
lst.count(str(lst[1]))

for i in range(10):
#     print(i)
    print(f'{i} : {lst.count(str(i))}')

['1', '7', '0', '3', '7', '3', '0', '0']
0 : 3
1 : 1
2 : 0
3 : 2
4 : 0
5 : 0
6 : 0
7 : 2
8 : 0
9 : 0


In [14]:
lst = list()

for i in range(10) : 
    num = int(input())
    lst.append(num%42)

print(set(lst))
len(set(lst))

42
84
252
420
840
126
42
84
420
126
{0}


1

In [42]:
check = 0
score = list()

num = int(input())
for i in range(num) :
    test_case = list(input())

    while True : # 테스트 케이스 'O', 'X' 
        for i in range(len(test_case)) : 
            if test_case[i] == 'O' :
                check += 1
                score.append(check)
                print(score)
            elif test_case[i] == 'X' :
                check = 0
        print(sum(score))
        break
    check = 0
    score.clear()
    

5
OOXXOXXOOO
[1]
[1, 2]
[1, 2, 1]
[1, 2, 1, 1]
[1, 2, 1, 1, 2]
[1, 2, 1, 1, 2, 3]
10
[]
OOXXOOXXOO
[1]
[1, 2]
[1, 2, 1]
[1, 2, 1, 2]
[1, 2, 1, 2, 1]
[1, 2, 1, 2, 1, 2]
9
[]
OXOXOXOXOXOXOX
[1]
[1, 1]
[1, 1, 1]
[1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1]
7
[]
OOOOOOOOOO
[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
55
[]
OOOOXOOOOXOOOOX
[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 1]
[1, 2, 3, 4, 1, 2]
[1, 2, 3, 4, 1, 2, 3]
[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4, 1]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
30
[]


In [ ]:
OOXXOXXOOO 
OOXXOOXXOO
OXOXOXOXOXOXOX
OOOOOOOOOO
OOOOXOOOOXOOOOX

In [ ]:
10
9
7
55
30

In [22]:
value = input()

try :
    #문자가 들어 왔을 때 
    print(ord(value))
except TypeError: 
    # 숫자일때 예외처리
    print(chr(int(value)))


51
3


In [26]:
n = int(input())
value = input()

len(value)

25
7000000000000000000000000


25

In [29]:
S = list(input())
alphabet = [chr(c) for c in range(ord('a'), ord('z')+1)]

print(S)
S in alphabet

test
['t', 'e', 's', 't']


False

In [46]:
S = list(input())

alpabet = [chr(c) for c in range(ord('a'), ord('z')+1)] # a-z까지 리스트 구현 

print(S)
# print(alphabet) # e = s[1], alphabet[4]
# S[1] in alphabet[4]

# for i, v in enumerate(alpabet): 
#     if alphabet[i] in S : 
#         print('YES!!',i+1) 
#     else:
#         print('No','-1')
    
# for i, v in enumerate(S) :
#     if S[i] in alphabet : 
#         print('YES', i)
#     else:
#         print('No')
        
        
for i in enumerate(alphabet):
    for j in enumerate(S):
        if S[i] in alphabet : 
            print('YES', i)

baek
['b', 'a', 'e', 'k']


TypeError: list indices must be integers or slices, not tuple

In [65]:
n = int(input())
R, S = input().split()

for i in range(len(S)):
    print(S[i] * int(R), end ='')

2
5


ValueError: not enough values to unpack (expected 2, got 1)

In [70]:
lst = ['a','b','c','b','b','a']

for i in range(len(lst)):
    

a a
a a
b b
b b
b b
c c
b b
b b
b b
b b
b b
b b
a a
a a


In [119]:
# 포인트 : 구분지어 카운팅하기 => count(변수)

str = input().upper() # 입력받은 스트링을 대문자로 바꿔준다. 왜? 출력은 대문자로 출력하니
s = list(set(str)) # 비교대상 문자를 확인 및 중복을 없애기 위해 셋 으로 -> 리스트로 변환 
c = list() #  카운트 하는 값들을 넣어주는 리스트 값 

for i in range(len(s)):
    c.append(str.count(s[i]))
    print(s[i], c[i])

print(s[c.index(max(c))]) #해당 인덱스의 문자는? 


Mississipi
I 4
M 1
P 1
S 4
I


In [73]:
str in s

False

In [13]:
n = 10
fibo = [0] *(n) #n의 길이만큼 초기값 선언
fibo[1] = 1
for i in range(2, n+1):
    fibo[i] = fibo[i-1] + fibo[i-2]
print(fibo)

IndexError: list assignment index out of range

In [10]:
n = 10
fibo = [0] *(n)
fibo

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [14]:
str = 'test'
set(str)


{'e', 's', 't'}

In [22]:
str = input()

# key = set(str)
value = 

test


TypeError: 'str' object is not callable

In [ ]:
# 스트링에서 한 글자만 추출 